title = "miner"

[owner]
name = "Loopring corporation"

[mysql]
    hostname = "127.0.0.1"
    port = "3306"
    user = "root"
    password = "111111"
    db_name = "loopring_miner"
    table_prefix = "lpr_"
    debug = false